apiVersion: v1
kind: Pod
metadata: 
 name: nginx
spec:
 containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: docker
    - name: trainer
      value: sekhar
    - name: duration
      value: 25hrs
    - name: DB_HOST
      value: db.admin.com
    - name: username
      value: selkarmanduri  