---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-developer
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["deployments","services","secrets","configMaps"]
  verbs: ["get","list","watch","create","update","delete"]
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: roboshop-read-rolebinding
  namespace: roboshop
subjects:
- kind: User
  name: suresh
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: roboshop-read-role 
  apiGroup: rbac.authorization.k8s.io